package com.tuempresa.storage.ops.domain;

public enum QrHandoffStage {
    DRAFT,
    QR_VALIDATED,
    BAG_TAGGED,
    STORED_AT_WAREHOUSE,
    READY_FOR_PICKUP,
    PICKUP_PIN_VALIDATED,
    DELIVERY_IDENTITY_VALIDATED,
    DELIVERY_LUGGAGE_VALIDATED,
    DELIVERY_APPROVAL_PENDING,
    DELIVERY_APPROVAL_GRANTED,
    DELIVERY_COMPLETED
}
