create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    full_name varchar(160) not null,
    email varchar(160) not null unique,
    password_hash varchar(120) not null,
    phone varchar(30),
    active boolean not null default true
);

create table user_roles (
    user_id bigint not null references users(id) on delete cascade,
    role varchar(40) not null,
    primary key (user_id, role)
);

create table cities (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    name varchar(120) not null unique,
    country varchar(80) not null,
    active boolean not null default true
);

create table tourist_zones (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    city_id bigint not null references cities(id),
    name varchar(140) not null,
    latitude double precision not null,
    longitude double precision not null,
    radius_km double precision not null
);

create table warehouses (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    city_id bigint not null references cities(id),
    zone_id bigint references tourist_zones(id),
    name varchar(140) not null,
    address varchar(220) not null,
    latitude double precision not null,
    longitude double precision not null,
    capacity integer not null,
    occupied integer not null default 0,
    active boolean not null default true,
    open_hour varchar(10) not null,
    close_hour varchar(10) not null,
    rules varchar(600)
);
