create table refresh_tokens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    token varchar(512) not null unique,
    user_id bigint not null references users(id),
    expires_at timestamp with time zone not null,
    revoked boolean not null default false
);

create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index idx_refresh_tokens_revoked on refresh_tokens(revoked);
