create table if not exists incident_messages (
    id bigint generated by default as identity primary key,
    incident_id bigint not null,
    author_id bigint not null,
    message varchar(500) not null,
    original_language varchar(5),
    created_at timestamp not null,
    updated_at timestamp not null,
    created_by varchar(255) not null default 'system',
    updated_by varchar(255) not null default 'system',
    constraint fk_incident_messages_incident
        foreign key (incident_id) references incidents(id),
    constraint fk_incident_messages_author
        foreign key (author_id) references users(id)
);

create index if not exists idx_incident_messages_incident_created
    on incident_messages (incident_id, created_at);
