create table reservations (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    user_id bigint not null references users(id),
    warehouse_id bigint not null references warehouses(id),
    start_at timestamp with time zone not null,
    end_at timestamp with time zone not null,
    status varchar(40) not null,
    total_price numeric(12,2) not null,
    qr_code varchar(80) not null unique,
    expires_at timestamp with time zone,
    cancel_reason varchar(240)
);

create table payment_attempts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    reservation_id bigint not null references reservations(id),
    amount numeric(12,2) not null,
    status varchar(30) not null,
    provider_reference varchar(80) not null unique
);

create table checkin_records (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    reservation_id bigint not null references reservations(id),
    operator_id bigint not null references users(id),
    notes varchar(400)
);

create table checkout_records (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    reservation_id bigint not null references reservations(id),
    operator_id bigint not null references users(id),
    notes varchar(400)
);

create table stored_item_evidences (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    reservation_id bigint not null references reservations(id),
    operator_id bigint not null references users(id),
    type varchar(30) not null,
    url varchar(300) not null,
    observation varchar(240)
);

create table incidents (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    reservation_id bigint not null references reservations(id),
    opened_by bigint not null references users(id),
    resolved_by bigint references users(id),
    status varchar(30) not null,
    description varchar(500) not null,
    resolution varchar(500),
    resolved_at timestamp with time zone
);

create table delivery_orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    reservation_id bigint not null references reservations(id),
    type varchar(30) not null,
    address varchar(220) not null,
    zone varchar(120),
    status varchar(30) not null,
    cost numeric(12,2) not null
);

create index idx_reservation_user on reservations(user_id);
create index idx_reservation_warehouse on reservations(warehouse_id);
create index idx_reservation_status on reservations(status);
create index idx_reservation_dates on reservations(start_at, end_at);
create index idx_payment_status on payment_attempts(status);
create index idx_incident_status on incidents(status);
create index idx_delivery_reservation on delivery_orders(reservation_id);
