alter table payment_attempts
    add column if not exists gateway_status varchar(120);

alter table payment_attempts
    add column if not exists gateway_message varchar(500);

create table if not exists payment_webhook_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    provider varchar(40) not null,
    event_id varchar(120) not null,
    event_type varchar(140),
    provider_reference varchar(120),
    payload_json text not null,
    processing_status varchar(40) not null,
    processed boolean not null default false,
    received_at timestamp with time zone not null,
    processed_at timestamp with time zone,
    error_message varchar(500),
    payment_attempt_id bigint,
    reservation_id bigint
);

create unique index if not exists uk_payment_webhook_provider_event
    on payment_webhook_events(provider, event_id);

create index if not exists idx_payment_webhook_reference
    on payment_webhook_events(provider_reference);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    user_id bigint not null references users(id),
    type varchar(60) not null,
    channel varchar(30) not null,
    status varchar(30) not null,
    title varchar(180) not null,
    message varchar(500) not null,
    payload_json text
);

create index if not exists idx_notifications_user_created
    on notifications(user_id, created_at desc);
