alter table users
    add column if not exists first_name varchar(80);

alter table users
    add column if not exists last_name varchar(80);

alter table users
    add column if not exists nationality varchar(80);

alter table users
    add column if not exists preferred_language varchar(10);

alter table users
    add column if not exists email_verified boolean not null default false;

alter table users
    add column if not exists email_verification_code varchar(20);

alter table users
    add column if not exists email_verification_expires_at timestamp with time zone;

alter table users
    add column if not exists birth_date date;

alter table users
    add column if not exists gender varchar(20);

alter table users
    add column if not exists profile_photo_path varchar(260);

alter table users
    add column if not exists address_line varchar(220);

alter table users
    add column if not exists city_name varchar(120);

alter table users
    add column if not exists country_name varchar(120);

alter table users
    add column if not exists primary_document_type varchar(40);

alter table users
    add column if not exists primary_document_number varchar(60);

alter table users
    add column if not exists secondary_document_type varchar(40);

alter table users
    add column if not exists secondary_document_number varchar(60);

alter table users
    add column if not exists emergency_contact_name varchar(120);

alter table users
    add column if not exists emergency_contact_phone varchar(30);

alter table users
    add column if not exists terms_accepted_at timestamp with time zone;

alter table delivery_orders
    add column if not exists driver_name varchar(120);

alter table delivery_orders
    add column if not exists driver_phone varchar(30);

alter table delivery_orders
    add column if not exists vehicle_type varchar(40);

alter table delivery_orders
    add column if not exists vehicle_plate varchar(30);

alter table delivery_orders
    add column if not exists current_latitude double precision;

alter table delivery_orders
    add column if not exists current_longitude double precision;

alter table delivery_orders
    add column if not exists eta_minutes integer;

alter table delivery_orders
    add column if not exists tracking_stage integer not null default 0;

alter table delivery_orders
    add column if not exists destination_latitude double precision;

alter table delivery_orders
    add column if not exists destination_longitude double precision;

alter table delivery_orders
    add column if not exists next_tracking_at timestamp with time zone;

create table if not exists delivery_tracking_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    delivery_order_id bigint not null references delivery_orders(id) on delete cascade,
    sequence_number integer not null,
    status varchar(30) not null,
    latitude double precision not null,
    longitude double precision not null,
    eta_minutes integer,
    message varchar(220)
);

create unique index if not exists uk_delivery_tracking_order_sequence
    on delivery_tracking_events(delivery_order_id, sequence_number);

create index if not exists idx_delivery_tracking_order_created
    on delivery_tracking_events(delivery_order_id, created_at desc);
